### PR TITLE
fixes Add scriv to this repository #28

### PR DESCRIPTION
**Pull request by khiron**
Note piqtree2 version moved from __init__.py to _version.py

Documentation is in the readme.me of the changelog.d folder

"scriv" is added to dev dependencies, but you might need to `pip install scriv` as well to get the command line tool

### CODE REVIEW

**Review by rmcar17 — CHANGES_REQUESTED** [review]
Would it be possible to revert the changes with the version in `__init__` and `_version.py`? `pyproject.toml` has version as dynamic and the change makes it unable to find it.

**Comment by khiron** [comment]
> Would it be possible to revert the changes with the version in `__init__`

maybe ... let me test it.  There was a reason we did it this way in cogent3, but I forget what that reason was.

**Comment by rmcar17** [comment]
Alternatively, I think adding this to the pyproject.toml might work:

```
[tool.setuptools.dynamic]
version = {attr = "piqtree2._version.__version__"}
```

**Comment by khiron** [comment]
Yes that would work too, but I can also do it in a way that will work as long as the package has a `__version__`

```toml
[tool.scriv]
version_command = "python -c 'import piqtree2; print(piqtree2.__version__)'"
```

**Comment by rmcar17** [comment]
What about:
```toml
[tool.scriv]
version = "literal: piqtree2/__init__.py: __version__"
```

**Comment by GavinHuttley** [comment]
The reason we chose the strategy we have within Cogent3 is because we use the Cogent3 version information internally and having a separate _version file avoids circular imports. I say go with the last suggestion of Roberts (which is similar to what you put into cogent3's scriv section), i.e.
```
version = "literal: piqtree2/__init__.py: __version__"
```
The nice thing about this approach is that the version information only needs to be modified in one place. Whereas at present within Cogent3 changing the version means we have to make the edit in two places.

@rmcar17 Is there meant to be a space after the ":"?

Now if only we could adopt the same approach with the project version field instead of just the scriv one. (At least using flit we can't.)

**Comment by GavinHuttley** [comment]
(We will also adopt this strategy within Cogent3 and all of our other repositories.)

**Comment by rmcar17** [comment]
> @rmcar17 Is there meant to be a space after the ":"?

Works with the space, and is how it was formatted in the [documentation](https://scriv.readthedocs.io/en/latest/configuration.html#literal-prefix). Missed the `src/` prefix though.

I've made the changes, will merge after CI runs

**Pull request merged**
